Dockerfile: Install latest plugins
Using latest=false, even in combination with --latest-specified
results in plugin errors such as this:

SEVERE  jenkins.InitReactorRunner(#onTaskFailed: Failed Loading plugin
Authentication Tokens API Plugin v1.53.v1c90fd9191a_b_
(authentication-tokens)
java.io.IOException: Failed to load: Authentication Tokens API Plugin
(authentication-tokens 1.53.v1c90fd9191a_b_)
 - Required plugin is disabled: Credentials Plugin (credentials)
 )